#!/bin/sh
set -e

case "$1" in
    remove|deconfigure|upgrade)
        if command -v systemctl >/dev/null; then
            systemctl --global disable secureboot-notify.path >/dev/null 2>&1 || true
        fi
        ;;
    failed-upgrade)
        ;;
esac

#DEBHELPER#

exit 0
